export const CUSTOM_TIMEZONE_VALUE = '__CUSTOM__'

export const TIMEZONES = [
	{ value: 'Europe/Kaliningrad', label: 'Калининград (UTC+2)' },
	{ value: 'Europe/Moscow', label: 'Москва (UTC+3)' },
	{ value: 'Europe/Samara', label: 'Самара (UTC+4)' },
	{ value: 'Asia/Yekaterinburg', label: 'Екатеринбург (UTC+5)' },
	{ value: 'Asia/Omsk', label: 'Омск (UTC+6)' },
	{ value: 'Asia/Krasnoyarsk', label: 'Красноярск (UTC+7)' },
	{ value: 'Asia/Irkutsk', label: 'Иркутск (UTC+8)' },
	{ value: 'Asia/Yakutsk', label: 'Якутск (UTC+9)' },
	{ value: 'Asia/Vladivostok', label: 'Владивосток (UTC+10)' },
	{ value: 'Asia/Magadan', label: 'Магадан (UTC+11)' },
	{ value: 'Asia/Kamchatka', label: 'Петропавловск-Камчатский (UTC+12)' },
	{ value: 'Europe/London', label: 'Лондон (UTC+0)' },
	{ value: 'Europe/Paris', label: 'Париж (UTC+1)' },
	{ value: 'Europe/Berlin', label: 'Берлин (UTC+1)' },
	{ value: 'Europe/Rome', label: 'Рим (UTC+1)' },
	{ value: 'Europe/Madrid', label: 'Мадрид (UTC+1)' },
	{ value: 'Europe/Athens', label: 'Афины (UTC+2)' },
	{ value: 'Europe/Kiev', label: 'Киев (UTC+2)' },
	{ value: 'Europe/Minsk', label: 'Минск (UTC+3)' },
	{ value: 'Europe/Istanbul', label: 'Стамбул (UTC+3)' },
	{ value: 'Asia/Almaty', label: 'Алматы (UTC+6)' },
	{ value: 'Asia/Tashkent', label: 'Ташкент (UTC+5)' },
	{ value: 'Asia/Baku', label: 'Баку (UTC+4)' },
	{ value: 'Asia/Tbilisi', label: 'Тбилиси (UTC+4)' },
	{ value: 'Asia/Yerevan', label: 'Ереван (UTC+4)' },
	{ value: CUSTOM_TIMEZONE_VALUE, label: 'Другое (ввести вручную)' }
]
